### ISSUE TITLE
binlog's commit ts less than last ts

### ISSUE THREAD

**Issue by phonzia** [pingcap/tidb-binlog#692] opened 2019-07-25 08:08 UTC
When I start drainer, there are lots of error says commit ts is less than last ts
I started drainer like this
```
sudo ./drainer -config ../conf/drainer.toml -initial-commit-ts 410003709545414657 &
```
and the log is 
```
2019/07/25 15:56:33 merge.go:305: [error] binlog's commit ts is 410003997877600257, and is less than the last ts 410003997877600257
2019/07/25 15:56:33 merge.go:305: [error] binlog's commit ts is 410003998703353857, and is less than the last ts 410003998703353857
2019/07/25 15:56:33 merge.go:305: [error] binlog's commit ts is 410003999516000257, and is less than the last ts 410003999516000257
2019/07/25 15:56:33 syncer.go:297: [info] [write save point]410003997169811457
2019/07/25 15:56:33 merge.go:305: [error] binlog's commit ts is 410004000328646657, and is less than the last ts 410004000328646657
2019/07/25 15:56:33 merge.go:305: [error] binlog's commit ts is 410004001141293057, and is less than the last ts 410004001141293057
2019/07/25 15:56:33 merge.go:305: [error] binlog's commit ts is 410004001953939458, and is less than the last ts 410004001953939458
2019/07/25 15:56:33 merge.go:305: [error] binlog's commit ts is 410004002753478659, and is less than the last ts 410004002753478659
2019/07/25 15:56:33 merge.go:305: [error] binlog's commit ts is 410004003566125057, and is less than the last ts 410004003566125057
2019/07/25 15:56:33 merge.go:305: [error] binlog's commit ts is 410004004378771457, and is less than the last ts 410004004378771457
2019/07/25 15:56:33 merge.go:305: [error] binlog's commit ts is 410004005217632257, and is less than the last ts 410004005217632257
```

and it do not sync any sql executed unless I before restarting drainer. If I restart it, it will sync the operation I execute before and stop syncing again.

**Comment by suzaku** [comment] 2019-07-25 08:42
It seems drainer received many unexpected duplicate binlogs. Can you reproduce this every time with the same `-initial-commit-ts`?

**Comment by phonzia** [comment] 2019-07-25 08:48
yes, It can be reproduced. The problem is gone when I give all the pump a fresh start by removing all the file of the pump. This is strange.

**Comment by suzaku** [comment] 2020-01-09 08:50
Since we have no further information for reproducing this issue, I'll close it for now.
Feel free to add details and reopen the issue.

**Closed by suzaku** 2020-01-09 08:50 UTC
