### ISSUE TITLE
Timestamp not fit when sync to mysql

### ISSUE THREAD

**Issue by phonzia** [pingcap/tidb-binlog#699] opened 2019-08-05 03:13 UTC
I have a backup mysql from tidb, but the timestamp on my backup mysql is eight hours diff from my tidb. If the timestamp from my tidb is "2019-08-03 00:00:00", It would be "2019-08-03 08:00:00" from mysql . I have check the timezone, tidb is set to SYSTEM, which is +8000, and mysql is "+08:00".
I didn't set any timezone when I set up pump/drainer, is there anything I missed?

**Comment by july2993** [comment] 2019-08-05 03:52
- so TiDB and MySQL are using the same timezone "+08:00"
- what's your tidb/drainer version?
- what's the system timezone of the server which drainer running ?

we will try if we can reproduce the problem

**Comment by phonzia** [comment] 2019-08-05 04:16
All the server is the same timezone "+08:00", however timezone variaty in tidb is 'SYSTEM' and in mysql is "+08:00", my tidb/drainer version is
Release Version: v2.1.11
I just use the pump/drainer to sync tidb to a mysql server, here is my table ddl;
```
CREATE TABLE `lucky_circle_season` (
  `id` bigint(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `beginTime` bigint(11) UNSIGNED NOT NULL,
  `endTime` bigint(11) UNSIGNED NOT NULL,
  `updatetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `beginTime` (`beginTime`),
  KEY `endTime` (`endTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=31469;
```

**Comment by july2993** [comment] 2019-08-05 04:37
can you show the result of
`SHOW VARIABLES LIKE '%time_zone%';` and `select now()` on both TiDB and mysql
@WangXiangUSTC PTAL

**Comment by phonzia** [comment] 2019-08-05 04:46
TIDB
+------------------+--------+
| Variable_name    | Value  |
+------------------+--------+
| system_time_zone | CST    |
| time_zone        | SYSTEM |
+------------------+--------+
+---------------------+
| now()               |
+---------------------+
| 2019-08-05 04:45:38 |
+---------------------+
mysql
+------------------+--------+
| Variable_name    | Value  |
+------------------+--------+
| system_time_zone | CST    |
| time_zone        | +08:00 |
+------------------+--------+
+---------------------+
| now()               |
+---------------------+
| 2019-08-05 12:45:23 |
+---------------------+

Now I see the differences, tidb select now() is not the time of the system, but
 why? how can I fix this?

**Comment by july2993** [comment] 2019-08-05 05:27
I guess the server timezone runnin TiDB is not the same as MySQL, pls check it.

**Comment by phonzia** [comment] 2019-08-05 05:27
I checked my system timezone use `date -R`
```
Mon, 05 Aug 2019 13:25:24 +0800
```

**Comment by phonzia** [comment] 2019-08-05 05:38
It looks like tidb didn't follow the timezone setting of system, and it works

**Comment by july2993** [comment] 2019-08-05 05:55
maybe a relate issue: https://github.com/pingcap/tidb/issues/9903
close this since this is unrelate to tidb-binlog actually.

**Closed by july2993** 2019-08-05 05:55 UTC
